//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC1_EntityFramework_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.CartInfoes = new HashSet<CartInfo>();
        }
    
        public int orderID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<double> totalCost { get; set; }
        public Nullable<bool> orderStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartInfo> CartInfoes { get; set; }
        public virtual User User { get; set; }
    }
}
